/*--------------------------------------------------------------------------
 * This file is autogenerated from config.h.in
 * during the cmake configuration of your project. If you need to make changes
 * edit the original file NOT THIS FILE.
 * --------------------------------------------------------------------------*/
#ifndef __LIBCUTIL_AUTOCONFIG_H
#define __LIBCUTIL_AUTOCONFIG_H


/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_STRTOQ 1

/* Define to 1 if you have the Stack Backtrace library. */
#define HAVE_BKTR 1

/* Define to 1 if you have the <> header file. */
/* #undef HAVE_WINSOCK_H */

/* Define to 1 if you have the <arpa/inet.h> header file. */
#define HAVE_ARPA_INET_H 1

/* Define to 1 if you have the <winsock2.h> header file. */
/* #undef HAVE_WINSOCK2_H */

/* Define to 1 if you have the `inet_aton' function. */
#define HAVE_INET_ATON 1

/* Define to 1 if your system defines the locale_t type in locale.h */
#define HAVE_LOCALE_T_IN_LOCALE_H

/* Define to 1 if your system defines the locale_t type in xlocale.h */
#define HAVE_LOCALE_T_IN_XLOCALE_H

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1


  /* Define to 1 if you have the <stddef.h> header file. */
#define HAVE_STDDEF_H 1

/* Define to 1 if you have <alloca.h> and it should be used (not on Ultrix).
   */
#define HAVE_ALLOCA_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1


/* Define if your system has the GLOB_NOMAGIC headers. */
/* #undef HAVE_GLOB_NOMAGIC */

/* Define if your system has the GLOB_BRACE headers. */
/* #undef HAVE_GLOB_BRACE */

/* Define to 1 if internal poll should be used. */
/* #undef AST_POLL_COMPAT */


/* Define to 1 if limits.h includes a LLONG_MAX definition. */
#define HAVE_LLONG_MAX 1

/* Define to 1 if you have the `closefrom' function. */
/* #undef HAVE_CLOSEFROM */

/* Define to 1 if you have the `roundl' function. */
#define HAVE_ROUNDL 1

/* Define to 1 if you have the `round' function. */
#define HAVE_ROUND 1

/* Define to 1 if you have the `roundf' function. */
#define HAVE_ROUNDF 1

/* Define to 1 if your system defines timersub. */
#define HAVE_TIMERSUB 1


/* Define to 1 if arpa/inet.h includes a htonll definition. */
/* #undef HAVE_HTONLL */
/* Define to 1 if arpa/inet.h includes a ntohll definition. */
/* #undef HAVE_NTOHLL */


/* Define to 1 if you have the `asprintf' function. */
#define HAVE_ASPRINTF 1


/* Define to 1 if you have the `ffsll' function. */
#define HAVE_FFSLL 1

/* Define to 1 if you have the `getloadavg' function. */
#define HAVE_GETLOADAVG 1

/* Define to 1 if you have the `mkdtemp' function. */
#define HAVE_MKDTEMP 1



/* Define to 1 if you have the `setenv' function. */
#define HAVE_SETENV 1

/* Define to 1 if you have the `strcasestr' function. */
#define HAVE_STRCASESTR 1

/* Define to 1 if you have the `strndup' function. */
#define HAVE_STRNDUP 1

/* Define to 1 if you have the `strnlen' function. */
#define HAVE_STRNLEN 1

/* Define to 1 if you have the `strsep' function. */
#define HAVE_STRSEP 1

/* Define to 1 if you have the `unsetenv' function. */
#define HAVE_UNSETENV 1

/* Define to 1 if you have the `vasprintf' function. */
#define HAVE_VASPRINTF 1

/* Define to 1 if you have the <sys/thr.h> header file. */
/* #undef HAVE_SYS_THR_H */


/* The size of `char *', as computed by sizeof. */
#define SIZEOF_CHAR_P 8

/* The size of `fd_set.fds_bits', as computed by sizeof. */
#define SIZEOF_FD_SET_FDS_BITS 8

/* The size of `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of `long', as computed by sizeof. */
#define SIZEOF_LONG 8

/* The size of `long long', as computed by sizeof. */
#define SIZEOF_LONG_LONG 8

/* Define to a type of the same size as fd_set.fds_bits[[0]] */
#define TYPEOF_FD_SET_FDS_BITS long

/* Define to 1 if you have the `gethostbyname' function. */
#define HAVE_GETHOSTBYNAME

/* Define to 1 if your system has gethostbyname_r with 5 arguments. */
/* #undef HAVE_GETHOSTBYNAME_R_5 */

/* Define to 1 if your system has gethostbyname_r with 6 arguments. */
#define HAVE_GETHOSTBYNAME_R_6

/* Define to 1 if you have the `gethostname' function. */
#define HAVE_GETHOSTNAME

/* Define if your system has the GETIFADDRS headers. */
#define HAVE_GETIFADDRS

/* Define to 1 if your system has the dladdr() GNU extension */
/* #undef HAVE_DLADDR */

/* Define to 1 if `fork' works. */
#define HAVE_WORKING_FORK 1

/* Define to 1 if `vfork' works. */
#define HAVE_WORKING_VFORK 1


/* Define to 1 if `getpeerid' works. */
/* #undef HAVE_GETPEEREID */

/* Define to 1 if `uid' is a member of `struct ucred'. */
/* #undef HAVE_STRUCT_UCRED_UID */

/* Define to 1 if `cr_uid' is a member of `struct ucred'. */
/* #undef HAVE_STRUCT_UCRED_CR_UID */

/* Define to 1 if `uid' is a member of `struct sockpeercred'. */
/* #undef HAVE_STRUCT_SOCKPEERCRED_UID */

/* Enable extensions on AIX 3, Interix.  */
#define _ALL_SOURCE 1

/* Enable GNU extensions on systems that have them.  */
#define _GNU_SOURCE 1

/* Enable threading extensions on Solaris.  */
#define _POSIX_PTHREAD_SEMANTICS 1

/* Enable extensions on HP NonStop.  */
#define _TANDEM_SOURCE 1

/* Enable general extensions on Solaris.  */
#define __EXTENSIONS__ 1


/* Enable extensions on AIX 3, Interix.  */
#ifndef _ALL_SOURCE
# undef _ALL_SOURCE
#endif
/* Enable GNU extensions on systems that have them.  */
#ifndef _GNU_SOURCE
# undef _GNU_SOURCE
#endif
/* Enable threading extensions on Solaris.  */
#ifndef _POSIX_PTHREAD_SEMANTICS
# undef _POSIX_PTHREAD_SEMANTICS
#endif
/* Enable extensions on HP NonStop.  */
#ifndef _TANDEM_SOURCE
# undef _TANDEM_SOURCE
#endif
/* Enable general extensions on Solaris.  */
#ifndef __EXTENSIONS__
# undef __EXTENSIONS__
#endif


/* Define to 1 for libcutl */
#define HAVE_LIBCUITL 1

#endif
